name: publish
on:
  push:
    branches: [development]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        always-auth: true
    - name: Build and publish
      run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
